FROM lpcontainerregistry.azurecr.io/aspnet-withfonts:4.8-windowsservercore-ltsc2022-20250130
# 2022 doesn't work on a win10 host


SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile vc_redist.x64.exe; \
    Start-Process -FilePath vc_redist.x64.exe -ArgumentList '/passive' -NoNewWindow -Wait; \
    Remove-Item -Force vc_redist.x64.exe
